apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ejabberd.fullname" . }}
  labels:
    {{- include "ejabberd.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ejabberd.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ejabberd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ejabberd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ejabberd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.postgresql.enabled }}
      initContainers:
        - name: wait-for-pg
          image: alpine
          command:
            - sh
            - '-c'
            - >-
              apk add -u net-tools postgresql &&
              echo -e "Waiting for PostgreSQL database..." &&
              while ! nc -z {{ .Values.postgresql.fullnameOverride }} {{ .Values.postgresql.primary.service.ports.postgresql }}; do sleep 1; done &&
              echo -e ">> PostgreSQL Server has started" &&
              echo -e "Applying ejabberd schema..." &&
              wget https://raw.githubusercontent.com/processone/ejabberd/{{ .Values.image.tag | default .Chart.AppVersion }}/sql/pg.new.sql &&
              PGPASSWORD={{ .Values.postgresql.auth.password }} psql -h {{ .Values.postgresql.fullnameOverride }} -U {{ .Values.postgresql.auth.username }} {{ .Values.postgresql.auth.database }} < ./pg.new.sql &&
              echo -e ">> Schema successfully applied";
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ERLANG_COOKIE
              value: {{ .Values.environment.erlangCookie }}
            - name: CTL_ON_CREATE
              value: {{ .Values.environment.ctlOnCreate }}
            - name: CTL_ON_START
              value: {{ .Values.environment.ctlOnStart }}
          ports:
            - name: xmpp
              containerPort: {{ .Values.service.port.xmpp }}
              protocol: TCP
            - name: fed
              containerPort: {{ .Values.service.port.fed }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.port.http }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.service.port.https }}
              protocol: TCP
            - name: mqtt
              containerPort: {{ .Values.service.port.mqtt }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Chart.Name }}-conf
              mountPath: /home/ejabberd/conf/ejabberd.yml
              subPath: ejabberd.yml
            - name: {{ .Chart.Name }}-conf
              mountPath: /home/ejabberd/conf/jwt.key
              subPath: jwt.key
            - name: {{ .Chart.Name }}-database
              mountPath: /home/ejabberd/database/
      volumes:
        - name: {{ .Chart.Name }}-conf
          configMap:
            name: {{ include "ejabberd.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: {{ .Chart.Name }}-database
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistence.size.database | quote }}
